### ISSUE TITLE
Display prefpane error.

### ISSUE THREAD

**Issue by jonnps** [xShiftx/Lenovo-300-17ISK-10.12-Clover#1]
You were able to open the Display prefpane?
![error](https://cloud.githubusercontent.com/assets/15981500/22915466/9aaf960e-f25e-11e6-9fb4-a4766052a1fa.png)

**Comment by xShiftx** [comment]
It's fixed in 10.12.4 :) I am try to edit EDID but it have no effect because EDID version is 1.4 on this laptop.
